"""add_transaction_metadata

Revision ID: 2c0d90338ed2
Revises: cc5c432fa36c
Create Date: 2026-05-22 20:13:24.187428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c0d90338ed2'
down_revision: Union[str, None] = 'cc5c432fa36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category_detailed', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_channel', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('pending', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transactions', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location_region', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'location_region')
    op.drop_column('transactions', 'location_city')
    op.drop_column('transactions', 'pending')
    op.drop_column('transactions', 'payment_channel')
    op.drop_column('transactions', 'category_detailed')
    op.drop_column('transactions', 'merchant_name')
    # ### end Alembic commands ###
