"""add_merchant_details

Revision ID: a3e2d91c99e5
Revises: 2c0d90338ed2
Create Date: 2026-05-22 20:17:39.375962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3e2d91c99e5'
down_revision: Union[str, None] = '2c0d90338ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant_website', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('merchant_logo_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('iso_currency_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('authorized_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'authorized_date')
    op.drop_column('transactions', 'iso_currency_code')
    op.drop_column('transactions', 'merchant_logo_url')
    op.drop_column('transactions', 'merchant_website')
    # ### end Alembic commands ###
