"""add_excluded_flag

Revision ID: edcbe7a3d4fa
Revises: a3e2d91c99e5
Create Date: 2026-05-22 20:50:48.515388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edcbe7a3d4fa'
down_revision: Union[str, None] = 'a3e2d91c99e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('excluded', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'excluded')
    # ### end Alembic commands ###
